name: Publish to Maven Central

on:
  push:
    tags:
      - 'v*'  # 例如 v1.0.0

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: sbt bloop sbtn
      - name: format check
        run: sbt scalafmtCheck
      - name: test
        run: sbt test
      - name: Import GPG key
        run: |
          echo "${{ secrets.PGP_PRIVATE_KEY }}" | gpg --batch --yes --import
          echo "use-agent" >> ~/.gnupg/gpg.conf
          echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo RELOADAGENT | gpg-connect-agent
          gpg --list-keys

      - name: Publish artifacts
        run: |
          sbt clean +publishSigned
          sbt sonatypeBundleRelease
