name: CI

on:
  push:
    branches: main
    paths-ignore:
      - '**/*.md'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: coursier/cache-action@v6
      - uses: coursier/setup-action@v1
        with:
          jvm: temurin:17
          apps: sbt bloop sbtn
      - name: format check
        run: sbt scalafmtCheckAll
      - name: test
        run: sbt test
